apiVersion: v1
kind: Service
metadata:
  name: simple-app-nodeport-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001 # range 30000-32768
  selector:
    app: simple-app
  type: NodePort